import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import NextUIProviders from './NextUiProvider'
import Header from '@/components/Header/page'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
    title: 'Next - NextUI',
    description: 'Generated by create next app',
}
interface RootLayoutProps {
    readonly children: React.ReactNode
};

const RootLayout = ({ children }: RootLayoutProps) => {

    return (
        <html lang="en">
            <body className={inter.className}>
                <NextUIProviders>
                    <Header />
                    <main className='mt-[65px]'>
                        {children}
                    </main>
                </NextUIProviders>
            </body>
        </html>
    )
}

export default RootLayout
